set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_VERSION 14.3)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(FREEBSD_TARGET "x86_64-unknown-freebsd14.3")

if(NOT DEFINED FREEBSD_SYSROOT)
  message(FATAL_ERROR "FREEBSD_SYSROOT is not set (path to FreeBSD base sysroot).")
endif()

set(CMAKE_SYSROOT "${FREEBSD_SYSROOT}")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET ${FREEBSD_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${FREEBSD_TARGET})

set(CMAKE_C_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT} -fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT} -fuse-ld=lld")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
